defaults: &defaults 
  working_directory: ~/repo
  docker:
    - image: circleci/node:10.13.0
  steps:
    - checkout
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "package.json" }}
        # fallback to using the latest cache if no exact match is found
        - v1-dependencies-
    - run: 
        name: Install packages
        command: npm install
    - save_cache:
        paths:
          - node_modules
        key: v1-dependencies-{{ checksum "package.json" }}
    - run: 
        name: Install python-dev
        command: sudo apt-get update && sudo apt-get install -y python-dev
    - run: 
        name: Install pip
        command: sudo curl -O https://bootstrap.pypa.io/get-pip.py && sudo python get-pip.py
    - run: 
        name: Install aws command line
        command: sudo pip install awscli --upgrade
    - run:
        name: Deploy
        command: CI=false npm run build && aws s3 sync build/ $S3_BUCKET --delete
version: 2
jobs:
  deploy-dev:
    environment:
      ENV: development
      # S3_BUCKET: s3://purchase-flow-dev.handytravel.tech/deal_purchase
      S3_BUCKET: s3://purchase-flow.handytravel.tech/deal_purchase
    <<: *defaults
  deploy-staging:
    environment:
      ENV: staging
      S3_BUCKET: s3://purchase-flow-stag.handytravel.tech/deal_purchase
    <<: *defaults
  deploy-production:
    environment:
      ENV: production
      S3_BUCKET: s3://purchase-flow.handy.travel/deal_purchase
    <<: *defaults
workflows:
  version: 2
  build_and_test:
    jobs:
      - deploy-staging:
          filters:
            branches:
              only: staging
      - deploy-dev:
          filters:
            branches:
              only: develop
      - deploy-production:
          filters:
            branches:
              only: master
